services:
  init:
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - DEVICE_ID=${DEVICE_ID:-}
      - TEDGE_C8Y_URL=${TEDGE_C8Y_URL:-$C8Y_DOMAIN}
      - C8Y_USER=${C8Y_USER:-}
      - C8Y_PASSWORD=${C8Y_PASSWORD:-}
    command:
      - sh
      - -c
      - (tedge cert show >/dev/null 2>&1 || tedge cert create --device-id "$DEVICE_ID") && tedge cert upload c8y
    volumes:
      - device-certs:/etc/tedge/device-certs
    profiles:
      - init
    networks:
      - tedge

  tedge:
    container_name: tedge
    build:
      dockerfile: Dockerfile
      context: .
    restart: always
    env_file:
      - .env
    environment:
      - DEVICE_ID=${DEVICE_ID:-}
      - TEDGE_C8Y_URL=${TEDGE_C8Y_URL:-$C8Y_DOMAIN}
    tmpfs:
      - /tmp
    volumes:
      - device-certs:/etc/tedge/device-certs
      - mosquitto:/mosquitto/data
      - /var/run/docker.sock:/var/run/docker.sock:rw
    profiles:
      - service
    networks:
      - tedge

volumes:
  device-certs:
    external: true
  mosquitto:
    external: true

networks:
  tedge:
    external: true
