operation = "self_update"

[init]
action = "proceed"
on_success = "schedule"

[schedule]
action = "proceed"
on_success = "executing"

[executing]
action = "proceed"
on_success = "needs_update"

[needs_update]
script = "self_update.sh needs_update --image ${.payload.image} --container-name ${.payload.containerName}"
on_exit.0 = "update"
on_exit.1 = "successful"
on_exit._ = "failed"

[update]
script = "self_update.sh update_background --image ${.payload.image} --container-name ${.payload.containerName}"
on_success = "verify"
on_error = "failed"

[verify]
script = "self_update.sh verify --image ${.payload.image} --container-name ${.payload.containerName}"
on_success = "successful"
on_error = "failed"

[successful]
action = "cleanup"

[failed]
action = "cleanup"
