operation = "self_update"

[init]
action = "proceed"
on_success = "executing"

[schedule]
action = "proceed"
on_success = "executing"

[executing]
action = "proceed"
on_success = "needs_update"

[needs_update]
script = "self_update.sh needs_update"
on_exit.0 = "update"
on_exit.1 = "successful"
on_exit._ = "failed"

[update]
script = "self_update.sh update_background"
on_success = "shutdown_container"
on_error = "failed"

[shutdown_container]
# Note: a restart will trigger a container shutdown
operation = "restart"
on_exec = "await_container_startup"

[await_container_startup]
action = "await-operation-completion"
on_success = "verify"

[verify]
# The container should be up to date after
# if it isn't then something went wrong
script = "self_update.sh needs_update"
on_exit.0 = "failed"
on_exit.1 = "successful"
on_exit._ = "failed"

[successful]
action = "cleanup"

[failed]
action = "cleanup"
