operation = "self_update"

[init]
action = "proceed"
on_success = "executing"

[schedule]
action = "proceed"
on_success = "executing"

[executing]
action = "proceed"
on_success = "update"

[needs_update]
# TODO: Prevent infinite loop
script = "self-update.sh needs_update"
on_exit.0 = "update"
on_exit.1 = "successful"
on_exit._ = "failed"

[update]
script = "self-update.sh update_background"
on_exec = "waiting-for-update"
on_success = "failed"
on_error = "failed"
# on_kill is expected as it is a sign that the background updater is working
# and needs_update is idempotent
on_kill = "needs_update"

[successful]
action = "cleanup"

[failed]
action = "cleanup"
