operation = "self_update"

[init]
action = "proceed"
on_success = "schedule"

[schedule]
action = "proceed"
on_success = "executing"

[executing]
action = "proceed"
on_success = "needs_update"

[needs_update]
script = "sudo -E tedge-container tools container-clone --image ${.payload.image} --container ${.payload.containerName} --check"
on_exit.0 = "update"
on_exit.2 = "successful"
on_exit._ = "failed"

[update]
script = "sudo -E tedge-container tools container-clone --fork --image ${.payload.image} --container ${.payload.containerName} --fork-name ${.payload.containerName}-updater --stop-after 10s"
on_success = "wait-for-container-stop"
on_error = "failed"

[wait-for-container-stop]
# Wait for the container to stop
background_script = "sleep 60"
on_exec = "resume-update"

[resume-update]
# Wait before verifying to give the container updater to verify the image
script = "sh -c 'sudo -E tedge-container self list && sleep 60'"
on_success = "needs_restart"
on_error = "needs_restart"

[needs_restart]
# if env. variable TEDGE_RESTART_ON_SELF_UPDATE is set and has value TRUE the updated container is restarted
script = "sh -c 'if [ ! -z "${TEDGE_RESTART_ON_SELF_UPDATE}" ] && [ "${TEDGE_RESTART_ON_SELF_UPDATE}" = "TRUE" ]; then exit 0; else exit 1; fi'"
on_success = "restart"
on_error = "collect-logs"

[restart]
# the cmd 'tedge-container tools container-restart' needs to be implemented in https://github.com/thin-edge/tedge-container-plugin/blob/main/cli/tools/cmd.go, as only container_clone, container_remove, ... exists
script = "sh -c 'sudo -E tedge-container tools container-restart ${.payload.containerName}'"
on_success = "collect-logs"
on_error = "collect-logs"

[collect-logs]
script = "sh -c 'sudo -E tedge-container tools container-logs ${.payload.containerName}-updater; sudo -E tedge-container tools container-remove ${.payload.containerName}-updater'"
on_success = "verify"
on_error = "verify"

[verify]
script = "sudo -E tedge-container tools container-clone --image ${.payload.image} --container ${.payload.containerName} --check"
# Expected 2 which means no update is required (as it should of already happened).
# If an update is still required, then it generally means something unexpected happened
on_exit.0 = { status = "failed", reason = "Container was not updated" }
on_exit.2 = "successful"
on_exit._ = { status = "failed", reason = "Unexpected error checking container status" }

[successful]
action = "cleanup"

[failed]
action = "cleanup"
