operation = "self_update"

[init]
action = "proceed"
on_success = "schedule"

[schedule]
action = "proceed"
on_success = "executing"

[executing]
action = "proceed"
on_success = "needs_update"

[needs_update]
script = "self_update.sh needs_update --image ${.payload.image}"
on_exit.0 = "update"
on_exit.1 = "successful"
on_exit._ = "failed"

[update]
script = "self_update.sh update_background --image ${.payload.image}"
on_success = "restart"
on_error = "failed"

[restart]
# Note: a restart will trigger a container shutdown
# and the new container will resume processing the operation
operation = "restart"
on_exec = "await_restart"

[await_restart]
# The new container will resume from this point
# (assuming the workflow state file is shared between the old and new container)
action = "await-operation-completion"
on_success = "verify"

[verify]
script = "self_update.sh verify --image ${.payload.image}"
on_success = "successful"
on_error = "failed"

[successful]
action = "cleanup"

[failed]
action = "cleanup"
