name: Publish

on:
  workflow_dispatch:
    inputs:
      VERSION:
        description: "Version"
        type: string
        default: ""
  push:
    tags:
      - "*"

jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: taiki-e/install-action@just

      - name: Publish images
        run: just publish registry ${{ inputs.VERSION || github.ref_name }}
